apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-book-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-book-api
  template:
    metadata:
      labels:
        app: go-book-api
    spec:
      containers:
        - name: go-book-api
          image: yourdockerhub/go-book-api:v1
          ports:
            - containerPort: 8080